# Generated by Django 4.2.2 on 2023-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
